// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// decimal2binary_cpp
LogicalVector decimal2binary_cpp(IntegerVector x, int n, int n_last);
RcppExport SEXP _simARG_decimal2binary_cpp(SEXP xSEXP, SEXP nSEXP, SEXP n_lastSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_last(n_lastSEXP);
    rcpp_result_gen = Rcpp::wrap(decimal2binary_cpp(x, n, n_last));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_simARG_decimal2binary_cpp", (DL_FUNC) &_simARG_decimal2binary_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_simARG(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
