# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert decimal rows to binary rows (Rcpp version)
#'
#' Convert every decimal number to `n` binary elements.
#'
#' @param x A integer vector.
#' @param n An integer.
#' @param n_last An integer as the number of binary elements for last value in `x`.
#' @return A boolean vector of binary numbers.
decimal2binary_cpp <- function(x, n, n_last) {
    .Call(`_simARG_decimal2binary_cpp`, x, n, n_last)
}

